//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="ServiceReference1.RssService")]
    public interface RssService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/RssService/getXMLRequest", ReplyAction="http://service/RssService/getXMLResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getXML(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/RssService/getXMLRequest", ReplyAction="http://service/RssService/getXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getXMLAsync(string arg0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RssServiceChannel : Client.ServiceReference1.RssService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.RssService>, Client.ServiceReference1.RssService {
        
        public RssServiceClient() {
        }
        
        public RssServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getXML(string arg0) {
            return base.Channel.getXML(arg0);
        }
        
        public System.Threading.Tasks.Task<string> getXMLAsync(string arg0) {
            return base.Channel.getXMLAsync(arg0);
        }
    }
}
